// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.yaw.model;

import br.com.yaw.model.Cliente;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Cliente_Roo_Configurable {
    
    declare @type: Cliente: @Configurable;
    
}
